export const FETCH_CURRENT_USER = "FETCH_CURRENT_USER";

export const SET_CURRENT_DISH = "SET_CURRENT_DISH";

export const SET_ACTIVE_PAGE = "SET_ACTIVE_PAGE";

export const SET_INGREDIENTS = "SET_INGREDIENTS";

export const SET_ACTIVE_PATIENT = "SET_ACTIVE_PATIENT";

export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";

export const ENQUEUE_SNACKBAR = "ENQUEUE_SNACKBAR";
