export const FETCH_CURRENT_USER = "FETCH_CURRENT_USER";

export const SET_CURRENT_DISH = "SET_CURRENT_DISH";

export const SET_ACTIVE_PAGE = "SET_ACTIVE_PAGE";

export const ENQUEUE_SNACKBAR = "ENQUEUE_SNACKBAR";
